name: Publish to Maven Central
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          cache: maven
      - name: Set up GPG Key
        run: |
          mkdir -p ~/.gnupg/
          chmod 700 ~/.gnupg/
          printf "$GPG_SIGNING_KEY" | base64 --decode > ~/.gnupg/private.key
          gpg --batch --import --passphrase "$GPG_PASSPHRASE" ~/.gnupg/private.key
        env:
          GPG_SIGNING_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
          GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
      - name: Publish package
        run: mvn -Prelease --batch-mode deploy -Dgpg.passphrase=${{ secrets.JRELEASER_GPG_PASSPHRASE }} --projects mailific-serverlib,mailific-server-spring-boot
        env:
          MAVEN_USERNAME: ${{ secrets.JRELEASER_NEXUS2_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.JRELEASER_NEXUS2_PASSWORD }}
